name: inride_driver
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  intl_utils: ^2.8.7
  provider: ^6.1.2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  go_router: ^14.4.1
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  google_maps_flutter: ^2.10.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/flutter_logo.png
    - assets/images/google.png
    - assets/images/twitter.png
    - assets/images/facebook.png
    - assets/images/location.png
    - assets/images/push_notification.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
